import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'article',
  title: 'Artikel',
  type: 'document',
  groups: [
    { name: 'content', title: 'Inhoud', default: true },
    { name: 'meta', title: 'Metadata' },
    { name: 'seo', title: 'SEO' },
    { name: 'relations', title: 'Relaties' },
    { name: 'moderation', title: 'Moderatie' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Titel',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required().min(10).max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: { source: 'title', maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'lead',
      title: 'Lead / intro',
      type: 'text',
      group: 'content',
      rows: 3,
      description: 'Korte samenvatting, wordt getoond op overzichtspagina en in meta description als SEO-veld leeg is.',
      validation: (rule) => rule.required().max(300),
    }),
    defineField({
      name: 'body',
      title: 'Artikel',
      type: 'array',
      group: 'content',
      of: [
        {
          type: 'block',
          styles: [
            { title: 'Normaal', value: 'normal' },
            { title: 'Kop 2', value: 'h2' },
            { title: 'Kop 3', value: 'h3' },
            { title: 'Citaat', value: 'blockquote' },
          ],
          marks: {
            decorators: [
              { title: 'Vet', value: 'strong' },
              { title: 'Cursief', value: 'em' },
            ],
            annotations: [
              {
                name: 'link',
                type: 'object',
                title: 'Link',
                fields: [{ name: 'href', type: 'url', title: 'URL' }],
              },
              {
                name: 'sourceRef',
                type: 'object',
                title: 'Bronverwijzing',
                description: 'Inline verwijzing naar een bron voor deze claim',
                fields: [
                  { name: 'source', type: 'reference', to: [{ type: 'source' }] },
                ],
              },
            ],
          },
        },
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', type: 'string', title: 'Alt-tekst' },
            { name: 'caption', type: 'string', title: 'Bijschrift' },
            { name: 'credit', type: 'string', title: 'Fotocredit' },
          ],
        },
      ],
    }),
    defineField({
      name: 'mainImage',
      title: 'Hoofdafbeelding',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [
        { name: 'alt', type: 'string', title: 'Alt-tekst' },
        { name: 'caption', type: 'string', title: 'Bijschrift' },
        { name: 'credit', type: 'string', title: 'Fotocredit / bron' },
      ],
    }),
    defineField({
      name: 'format',
      title: 'Format',
      type: 'string',
      group: 'meta',
      options: {
        list: [
          { title: 'Nieuwsbericht', value: 'news' },
          { title: '112 / kort', value: 'brief' },
          { title: 'Analyse', value: 'analysis' },
          { title: 'Feature', value: 'feature' },
          { title: 'Interview', value: 'interview' },
          { title: 'Reportage', value: 'reportage' },
        ],
        layout: 'radio',
      },
      initialValue: 'news',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'priority',
      title: 'Prioriteit',
      type: 'string',
      group: 'meta',
      description: 'Bepaalt visuele hiërarchie op de homepage',
      options: {
        list: [
          { title: 'Topverhaal', value: 'top' },
          { title: 'Normaal', value: 'normaal' },
          { title: 'Kort bericht', value: 'kort' },
        ],
        layout: 'radio',
      },
      initialValue: 'normaal',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'meta',
      options: {
        list: [
          { title: 'Concept', value: 'draft' },
          { title: 'Review', value: 'review' },
          { title: 'Gepubliceerd', value: 'published' },
          { title: 'Offline (melding)', value: 'flagged' },
          { title: 'Gearchiveerd', value: 'archived' },
        ],
      },
      initialValue: 'draft',
      validation: (rule) => rule.required(),
    }),
    defineField({ name: 'publishedAt', title: 'Publicatiedatum', type: 'datetime', group: 'meta' }),
    defineField({
      name: 'updatedAt',
      title: 'Laatst bijgewerkt',
      type: 'datetime',
      group: 'meta',
      description: 'Wanneer het artikel inhoudelijk is gewijzigd na publicatie',
    }),
    defineField({
      name: 'author',
      title: 'Auteur',
      type: 'string',
      group: 'meta',
      initialValue: 'AI-redactie Amersfoort Lokaal',
      description: 'Standaard AI-redactie. Pas aan als een mens het artikel heeft bewerkt.',
    }),
    defineField({
      name: 'editedBy',
      title: 'Bewerkt door',
      type: 'string',
      group: 'meta',
      description: 'Naam van menselijke bewerker, indien van toepassing',
    }),
    defineField({
      name: 'aiTransparency',
      title: 'AI-transparantie',
      type: 'text',
      group: 'meta',
      rows: 2,
      description: 'Korte uitleg hoe dit artikel tot stand is gekomen (welke bronnen, welke AI-stappen)',
      initialValue: 'Dit artikel is geschreven door een AI-redactie op basis van openbare bronnen.',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'tag' }] }],
    }),
    defineField({
      name: 'locations',
      title: 'Locaties / wijken',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'location' }] }],
    }),
    defineField({
      name: 'persons',
      title: 'Genoemde personen',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'person' }] }],
    }),
    defineField({
      name: 'organizations',
      title: 'Genoemde organisaties',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'organization' }] }],
    }),
    defineField({
      name: 'sources',
      title: 'Bronnen',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'source' }] }],
    }),
    defineField({
      name: 'relatedArticles',
      title: 'Gerelateerde artikelen',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'article' }], weak: true }],
      description: 'Handmatig of door de routine gekoppelde artikelen',
    }),
    defineField({
      name: 'signals',
      title: 'Onderliggende signalen',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'signal' }] }],
      description: 'De signalen waaruit dit artikel is voortgekomen',
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO-titel',
      type: 'string',
      group: 'seo',
      description: 'Overschrijft de titel in zoekmachines. Leeg = gewone titel.',
      validation: (rule) => rule.max(60),
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO-beschrijving',
      type: 'text',
      group: 'seo',
      rows: 2,
      description: 'Overschrijft de lead als meta description. Leeg = lead.',
      validation: (rule) => rule.max(160),
    }),
    defineField({
      name: 'reportCount',
      title: 'Aantal meldingen',
      type: 'number',
      group: 'moderation',
      initialValue: 0,
      readOnly: true,
      description: 'Wordt automatisch bijgewerkt door de frontend',
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'format', media: 'mainImage', status: 'status' },
    prepare({ title, subtitle, media, status }: any) {
      const statusIcons: Record<string, string> = {
        draft: '📝', review: '👁', published: '✅', flagged: '⚠️', archived: '📦',
      }
      return { title: `${statusIcons[status] || ''} ${title}`, subtitle, media }
    },
  },
  orderings: [
    { title: 'Publicatiedatum (nieuwst)', name: 'publishedAtDesc', by: [{ field: 'publishedAt', direction: 'desc' }] },
    { title: 'Meldingen (meest)', name: 'reportCountDesc', by: [{ field: 'reportCount', direction: 'desc' }] },
  ],
})
